### ISSUE TITLE
simple combustion generator issue

### ISSUE THREAD

**Issue by Frunblumglin** [ValkyrieofNight/SimpleGenerators#10]
### Description of the issue:
The simple combustion generator, when provided a fuel source that has something that should not be consumed like a lava bucket (or in my case the lava crystal from blood magic) the non-consumable item is consumed. i.e. the bucket.

### Versions & Modlist
![image](https://user-images.githubusercontent.com/13581892/39226385-06dfcb6a-4807-11e8-89be-37adf04398e9.png)

Forge: 14.23.2.2651
simple generators: 1.12.2-2.0.9a

Way of time has outlined an example of what may be happening in my original post:
[https://github.com/Darkosto/SevTech-Ages/issues/2033](url)

**Comment by ValkyrieofNight** [comment]
Fixed in 2.0.12a
