### ISSUE TITLE
[2.0.8a] Simple Combustion Generator bug with lava buckets

### ISSUE THREAD

**Issue by Aedda** [ValkyrieofNight/SimpleGenerators#12]
If you insert a lava bucket into a Simple Combustion Generator it will accept the bucket, consume the lava, consume the bucket, and only gives the burn time of a piece of coal (80s) not the burn time of a lava bucket (1000s) in a furnace.

**Comment by ValkyrieofNight** [comment]
Fixed in 2.0.12a
