### ISSUE TITLE
[1.12.2] Simple Generators Crashed While Loading Forge (1/7)

### ISSUE THREAD

**Issue by PulseBeat02** [ValkyrieofNight/SimpleGenerators#16]
While I was loading my big modpack, it crashed with an error. 

Minecraft Version: 1.12.2
Forge Version: 14.23.4.2765 
Simple Generators Version: 1.12.2-2.0.17.1

The crash report is here: https://pastebin.com/AhpEPXHP

Can anyone tell me what's going on?

**Comment by ValkyrieofNight** [comment]
I'm not sure why that error is happening but I will look more into it when I get home. Try re downloading valkyrielib 2.0.17.1 and see if that fixes it.

**Comment by PulseBeat02** [comment]
I have redownloaded it before and it still doesn’t work.

**Comment by ValkyrieofNight** [comment]
I figured out the problem and am working on a fix. A temporary fix would be to install JEI

**Comment by PulseBeat02** [comment]
I can’t install JEI because of my huge 582 modpack. However, I will be looking forward to a new update 👍🏻.

**Comment by ValkyrieofNight** [comment]
Just uploaded the fixes now :P You'll need to update both ValkyrieLib to 2.0.17.2 and Simple Gens to 2.0.17.2. Thanks for the bug report and feel free to re-open this issue if the problem persists :D

**Comment by ValkyrieofNight** [comment]
Oh btw the files might take an hour or two to appear on the twitch launcher :P

**Comment by PulseBeat02** [comment]
Alright. Thank you! 🙏
