### ISSUE TITLE
Using buckets on any generators does not consume the bucket but puts 1000mb into the gen

### ISSUE THREAD

**Issue by Poke5555** [ValkyrieofNight/SimpleGenerators#17]
when using a bucket on any generator it doesnt consume the bucket but it puts 1 buckets worth of fluid into the generator.
opening the gui and putting the bucket in works properly and so does pumping it in.
on version 1.12.2-2.0.17.2

**Comment by ValkyrieofNight** [comment]
ok thanks for the bug report will have a fix out next release hopefully

**Comment by ValkyrieofNight** [comment]
fixed in version 2.0.18.1
