### ISSUE TITLE
Issue with Tinker's crafting table & generators

### ISSUE THREAD

**Issue by Muddr** [ValkyrieofNight/SimpleGenerators#18]
Created an issue over on Tinker's repo and they mentioned that this would be an issue on your side.  

Link to issue SlimeKnights/TinkersConstruct#3667

**Comment by ValkyrieofNight** [comment]
Will look into it tonight

**Comment by ValkyrieofNight** [comment]
Found the error in the code. Will have a fix out in next release which should be out by the weekend

**Comment by ValkyrieofNight** [comment]
fixed in version 2.0.18.1
