### ISSUE TITLE
[1.12.2] Simple Generators Crashes While Loading Forge

### ISSUE THREAD

**Issue by Kainmortal** [ValkyrieofNight/SimpleGenerators#20]
Simple Generators makes forge load slower and after that crashes the startup, pls help :c

Minecraft Version: 1.12.2
Forge Version: 14.23.5.2811
Simple Generators Version: 1.12.2-2.0.20.1

Here is the crash report:[crash-2019-03-31_00.45.38-client.txt](https://github.com/ValkyrieofNight/SimpleGenerators/files/3026327/crash-2019-03-31_00.45.38-client.txt)

**Comment by ValkyrieofNight** [comment]
Will have a fix out today

**Comment by Kainmortal** [comment]
Thanks a lot for fixing!!
I really like the mod.. simple c:
