### ISSUE TITLE
1.12 update

### ISSUE THREAD

**Issue by ghost** [ValkyrieofNight/SimpleGenerators#8]
Are you going to update this mod for 1.12

**Comment by Griffdith** [comment]
Yes, please do update this. It’s a nice super simple mod that dose what it’s ment to.

**Comment by ValkyrieofNight** [comment]
Update in progress just haven't had a lot of time to work on it. Hopefully can get it finished soon.

**Comment by Griffdith** [comment]
Ok, thank you. Keep up the good work!
